# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb8fa65ef560e5552320efbda124cc6587b1c509479561a71a7cd5b83d8b92e4013792d85672aaa90183114b320e3bdb8cb85af8bb9d9db938d46cc122340940

test:
  secret_key_base: 3c3c2ecd00b1acf178aaec9c461efcb3cfca0cb98b578d2ffa0c1ece787bcb7d03c98f2dc3b71b38e89e5302dafafae9b79a4b7790c7224903400992699b4832

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
